//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapidemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public int ID { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public Nullable<int> rollno { get; set; }
        public string student_address { get; set; }
        public string student_state { get; set; }
        public Nullable<int> mobile { get; set; }
    }
}
